[env:esp32-s3-devkitc-1]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

lib_deps =
    mikalhart/TinyGPSPlus@^1.0.3
    sandeepmistry/LoRa@^0.8.0
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit INA219@^1.2.3
    adafruit/Adafruit BusIO@^1.16.1

monitor_speed  = 115200
upload_speed   = 921600
build_flags    = -DCORE_DEBUG_LEVEL=3
